PRAGMA foreign_keys = 1;

CREATE TABLE IF NOT EXISTS users (
  id INTEGER PRIMARY KEY NOT NULL,
  username VARCHAR(100) NULL DEFAULT NULL,
  password VARCHAR(200) NULL DEFAULT NULL,
  role INTEGER NULL DEFAULT NULL
);

CREATE TABLE IF NOT EXISTS machines (
  id INTEGER PRIMARY KEY NOT NULL,
  name VARCHAR(100) NULL DEFAULT NULL,
  ip_address VARCHAR(100) NULL DEFAULT NULL,
  location VARCHAR(100) NULL DEFAULT NULL
);

CREATE TABLE IF NOT EXISTS items (
  id INTEGER PRIMARY KEY NOT NULL,
  name VARCHAR(100) NULL DEFAULT NULL,
  detail MEDIUMTEXT NULL DEFAULT NULL,
  category INTEGER NOT NULL,
  image VARCHAR(120) NULL DEFAULT NULL,
  price BIGINT NULL DEFAULT NULL
);

CREATE TABLE IF NOT EXISTS category (
  id INTEGER PRIMARY KEY NOT NULL,
  name VARCHAR(100) NULL DEFAULT NULL
);
		
CREATE TABLE IF NOT EXISTS stock (
  id INTEGER PRIMARY KEY NOT NULL,
  item_id INTEGER NOT NULL,
  machine_id INTEGER NOT NULL,
  amount INTEGER NULL DEFAULT NULL
);

INSERT INTO users(id, username, password, role) 
SELECT 1, 'admin', '123', 1
WHERE NOT EXISTS(SELECT 1 FROM users WHERE id = 1);